### ISSUE TITLE
No build file

### ISSUE THREAD

**Issue by liviutudor** [PvdBerg1998/PNet#1]
Would you welcome a PR with a gradle build file for this?

**Comment by eitch** [comment]
And how about a Maven build file? I could offer that.

**Comment by PvdBerg1998** [comment]
@eitch Ofcourse. I had a quick look at Maven but I've never really used it before. When I changed the project structure to /src/main/java/... and src/test/java/... all the classes got messed up, eg. main.java.nl.pvdberg.pnet.packet.Packet instead of nl.pvdberg.pnet.packet.Packet. After that I figured it didn't really have any priority and gave up on it.

**Comment by eitch** [comment]
@PvdBerg1998 Are you using IntelliJ?

**Comment by PvdBerg1998** [comment]
@eitch I am. Just a normal empty project.
